import os
import sys
import zipfile
from pathlib import Path
from vdx.api import make_vault_request, API_VERSION
from vdx.utils import compute_checksum

def run_package(args):
    base_dir = "components"
    vpk_filename = "vdx_deployment.vpk"
    template_path = os.path.join("templates", "vaultpackage.xml")
    
    if not os.path.exists(base_dir):
        print("No /components directory found.")
        sys.exit(1)
        
    print(f"Packaging local components into {vpk_filename}...")
    
    with zipfile.ZipFile(vpk_filename, 'w', zipfile.ZIP_DEFLATED) as vpk:
        with open(template_path, 'r', encoding='utf-8') as tf:
            manifest_template = tf.read()
            
        manifest = manifest_template.format(
            package_name="vdx_deployment",
            author="vdx_tool",
            summary="Automated VPK generated by vdx",
            description="Custom VPK generated from local source control"
        )
        vpk.writestr("vaultpackage.xml", manifest)
        
        step_num = 10
        for root, dirs, files in os.walk(base_dir):
            for file in files:
                if file.endswith(".mdl"):
                    file_path = os.path.join(root, file)
                    path_parts = Path(file_path).parts
                    comp_type = path_parts[-2]
                    comp_name = file.replace(".mdl", "")
                    
                    step_folder = f"{step_num:06d}"
                    with open(file_path, 'r', encoding='utf-8') as f:
                        mdl_content = f.read()
                        
                    md5_hash = compute_checksum(mdl_content)
                    
                    vpk.writestr(f"components/{step_folder}/{comp_type}.{comp_name}.mdl", mdl_content)
                    vpk.writestr(f"components/{step_folder}/{comp_type}.{comp_name}.md5", f"{md5_hash} {comp_type}.{comp_name}")
                    
                    step_num += 10
                    
    print(f"Successfully created custom package {vpk_filename}.")
    print("Importing VPK to Vault...")
    import_endpoint = f"/api/{API_VERSION}/vpackages"
    
    with open(vpk_filename, 'rb') as f:
        response = make_vault_request("POST", import_endpoint, files={'file': (vpk_filename, f, 'application/zip')})
        
    if response.status_code == 200 and response.json().get("responseStatus") == "SUCCESS":
        package_id = response.json().get("data", {}).get("package_id__v")
        print(f"Package successfully imported. Vault Package ID: {package_id}")
        
        val_res = make_vault_request("POST", f"/api/{API_VERSION}/vpackages/{package_id}/actions/validate")
        if val_res.status_code == 200:
            print(f"Validation Job initiated successfully.")
    else:
        print(f"Error importing package: {response.text}")
